import type {ArraySpec, FormValue} from '../../../../../core';
import {SpecTypes} from '../../../../../core';

export const MULTI_SELECT: Record<string, ArraySpec> = {
    default: {
        type: SpecTypes.Array,
        enum: [
            'foo',
            'bar',
            'rab',
            'oof',
            'fooBar',
            'fooOof',
            'barFoo',
            'barOof',
            'fooFoo',
            'barBar',
        ],
        description: {
            foo: 'Option 1',
            bar: 'Option 2',
            rab: 'Option 3',
            oof: 'Option 4',
            fooBar: 'Option 5',
            fooOof: 'Option 6',
            barFoo: 'Option 7',
            barOof: 'Option 8',
            fooFoo: 'Option 9',
            barBar: 'Option 10',
        },
        viewSpec: {
            type: 'select',
            layout: 'row',
            layoutTitle: 'Select',
            placeholder: 'placeholder text',
            selectParams: {
                filterPlaceholder: 'filter placeholder',
                meta: {
                    foo: 'Additional text 1',
                    bar: 'Additional text 2',
                    rab: 'Additional text 3',
                    oof: 'Additional text 4',
                    fooBar: 'Additional text 5',
                    fooOof: 'Additional text 6',
                    barFoo: 'Additional text 7',
                    barOof: 'Additional text 8',
                    fooFoo: 'Additional text 9',
                    barBar: 'Additional text 10',
                },
            },
        },
    },
    defaultValue: {
        defaultValue: ['foo'],
        type: SpecTypes.Array,
        enum: [
            'foo',
            'bar',
            'rab',
            'oof',
            'fooBar',
            'fooOof',
            'barFoo',
            'barOof',
            'fooFoo',
            'barBar',
        ],
        description: {
            foo: 'Option 1',
            bar: 'Option 2',
            rab: 'Option 3',
            oof: 'Option 4',
            fooBar: 'Option 5',
            fooOof: 'Option 6',
            barFoo: 'Option 7',
            barOof: 'Option 8',
            fooFoo: 'Option 9',
            barBar: 'Option 10',
        },
        viewSpec: {
            type: 'select',
            layout: 'row',
            layoutTitle: 'Select',
            placeholder: 'placeholder text',
            selectParams: {
                filterPlaceholder: 'filter placeholder',
                meta: {
                    foo: 'Additional text 1',
                    bar: 'Additional text 2',
                    rab: 'Additional text 3',
                    oof: 'Additional text 4',
                    fooBar: 'Additional text 5',
                    fooOof: 'Additional text 6',
                    barFoo: 'Additional text 7',
                    barOof: 'Additional text 8',
                    fooFoo: 'Additional text 9',
                    barBar: 'Additional text 10',
                },
            },
        },
    },
    required: {
        required: true,
        type: SpecTypes.Array,
        enum: [
            'foo',
            'bar',
            'rab',
            'oof',
            'fooBar',
            'fooOof',
            'barFoo',
            'barOof',
            'fooFoo',
            'barBar',
        ],
        description: {
            foo: 'Option 1',
            bar: 'Option 2',
            rab: 'Option 3',
            oof: 'Option 4',
            fooBar: 'Option 5',
            fooOof: 'Option 6',
            barFoo: 'Option 7',
            barOof: 'Option 8',
            fooFoo: 'Option 9',
            barBar: 'Option 10',
        },
        viewSpec: {
            type: 'select',
            layout: 'row',
            layoutTitle: 'Select',
            placeholder: 'placeholder text',
            selectParams: {
                filterPlaceholder: 'filter placeholder',
                meta: {
                    foo: 'Additional text 1',
                    bar: 'Additional text 2',
                    rab: 'Additional text 3',
                    oof: 'Additional text 4',
                    fooBar: 'Additional text 5',
                    fooOof: 'Additional text 6',
                    barFoo: 'Additional text 7',
                    barOof: 'Additional text 8',
                    fooFoo: 'Additional text 9',
                    barBar: 'Additional text 10',
                },
            },
        },
    },
    desription: {
        type: SpecTypes.Array,
        enum: [
            'foo',
            'bar',
            'rab',
            'oof',
            'fooBar',
            'fooOof',
            'barFoo',
            'barOof',
            'fooFoo',
            'barBar',
        ],
        description: {
            foo: 'Option 1',
            bar: 'Option 2',
            rab: 'Option 3',
            oof: 'Option 4',
            fooBar: 'Option 5',
            fooOof: 'Option 6',
            barFoo: 'Option 7',
            barOof: 'Option 8',
            fooFoo: 'Option 9',
            barBar: 'Option 10',
        },
        viewSpec: {
            type: 'select',
            layout: 'row',
            layoutTitle: 'Select',
            placeholder: 'placeholder text',
            layoutDescription: 'description',
            selectParams: {
                filterPlaceholder: 'filter placeholder',
                meta: {
                    foo: 'Additional text 1',
                    bar: 'Additional text 2',
                    rab: 'Additional text 3',
                    oof: 'Additional text 4',
                    fooBar: 'Additional text 5',
                    fooOof: 'Additional text 6',
                    barFoo: 'Additional text 7',
                    barOof: 'Additional text 8',
                    fooFoo: 'Additional text 9',
                    barBar: 'Additional text 10',
                },
            },
        },
    },
    row_verbose: {
        type: SpecTypes.Array,
        enum: [
            'foo',
            'bar',
            'rab',
            'oof',
            'fooBar',
            'fooOof',
            'barFoo',
            'barOof',
            'fooFoo',
            'barBar',
        ],
        description: {
            foo: 'Option 1',
            bar: 'Option 2',
            rab: 'Option 3',
            oof: 'Option 4',
            fooBar: 'Option 5',
            fooOof: 'Option 6',
            barFoo: 'Option 7',
            barOof: 'Option 8',
            fooFoo: 'Option 9',
            barBar: 'Option 10',
        },
        viewSpec: {
            type: 'select',
            layout: 'row_verbose',
            layoutTitle: 'Select',
            placeholder: 'placeholder text',
            layoutDescription: 'description',
            selectParams: {
                filterPlaceholder: 'filter placeholder',
                meta: {
                    foo: 'Additional text 1',
                    bar: 'Additional text 2',
                    rab: 'Additional text 3',
                    oof: 'Additional text 4',
                    fooBar: 'Additional text 5',
                    fooOof: 'Additional text 6',
                    barFoo: 'Additional text 7',
                    barOof: 'Additional text 8',
                    fooFoo: 'Additional text 9',
                    barBar: 'Additional text 10',
                },
            },
        },
    },
};

export const VALUE: FormValue = ['foo', 'bar', 'barOof'];
